export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const FETCH_POSTS_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POST_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const PERSIST_POST_REQUEST = "PERSIST_POST_REQUEST";
export const PERSIST_POST_SUCCESS = "PERSIST_POST_SUCCESS";
export const PERSIST_POST_FAILURE = "PERSIST_POST_FAILURE";

export const FETCH_OWNER_REQUEST = "PERSIST_POST_REQUEST";
export const FETCH_OWNER_SUCCESS = "PERSIST_POST_SUCCESS";
export const FETCH_OWNER_FAILURE = "PERSIST_POST_FAILURE";
